block.go
block_test.go

This pull request remove the error return from the Block.Sha function since it can never fail and ends up causing a lot of unneeded error checking throughout the code base.

Remove error return from Block.Sha function.

---

.travis.yml
goclean.sh

Also, import the goclean.sh script directly into this repository and call it directly instead of using a remote gist.

Use container-based builds on TravisCI.

---

bloom/merkleblock.go

This pull request modifies the `NewMerkleBlock` function to return the matched transaction indices instead of their hashes.  This is being done because it is much easier for the caller to lookup the matched transactions from the original passed block based on their transaction index within the block versus their hashes.

Return matched tx indices from NewMerkleBlock.

---

block.go
block_test.go

This pull request depends on btcsuite/btcd#481.
This pull request converts all block height references to int32 instead of int64.  The current target block production rate is 10 mins per block which means it will take roughly 40,800 years to reach the maximum
height an int32 affords.  Even if the target rate were lowered to one block per minute, it would still take roughly another 4,080 years to reach the maximum.
In the mean time, there is no reason to use a larger type which results in higher memory usage.

Convert block heights to int32.

---

txsort.go
txsort_test.go

Here is the sorting function moved from btcd/wire (previous pull request: btcsuite/btcd#523 )
I have added txsort_test.go but there are no transactions in block 10000 which are "unsorted" (most have only 1 input).  Transaction[1] from block 10001 is unsorted and would be changed by this function, but writing that all in by hand is annoying :) 
Are there other blocks formatted like block 10000 for testing already in btcd?  Or is there some utility to format blocks or txs?  If there is I can put more tests that actually change the txid.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcutil/58)

Transaction input and output sorting

---

txsort/README.md
txsort/doc.go
txsort/txsort.go
txsort/txsort_test.go

This converts the txsort code into a separate package and renames `TxSort` and `IsTxSorted` to `Sort` and `IsSorted`, respectively.
It also adds a `doc.go` and `README.md` so it is consistent with the other packages.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcutil/59)

txsort: Convert to package

---

README.md
base58/README.md
bloom/README.md
coinset/README.md
hdkeychain/README.md
txsort/README.md

First, it removes the documentation section from all the `README.md` files and instead puts a web-based godoc badge and link at the top with the other badges. This is being done since the local `godoc` tool no longer ships with Go by default, so the instructions no longer work without first installing `godoc`. Due to this, pretty much everyone uses the web-based godoc these days anyways. Anyone who has manually installed `godoc` won't need instructions.
Second, it makes sure the ISC license badge is at the top with the other badges and removes the textual reference in the overview section.
Third, it's modifies the Installation section to Installation and Updating and adds a `-u` to the `go get` command since it works for both and thus is simpler.
Finally, it replaces the badges with SVG …

docs: Make various README.md files consistent.

---

hdkeychain/example_test.go
hdkeychain/extendedkey.go
hdkeychain/extendedkey_test.go

This changes the `NewMaster` function to accept the network the generated extended master key is associated with.  This could previously be done by calling `SetNet` on the returned extended key, but that approach is more error prone since it is easy for a caller to forget to do it or never know they should to begin with.
Closes #65
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcutil/66)

hdkeychain: Update NewMaster to accept network.

---

hdkeychain/extendedkey.go
hdkeychain/extendedkey_test.go

This corrects an issue with the serialization of extended private keys where certain underlying derivations could cause lead to printing extended privkeys that did not have the expected xprv prefix.
In addition, tests for private key derivation have been added as well as a specific test which triggers the previously failing case.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcutil/67)

hdkeychain: Correct extended privkey serialization.

---

bloom/filter.go
bloom/filter_test.go

Tiny fix here.  If you gave an argument of 0 for the false positive rate in NewFilter(), it would make a 0-length filter, always matching.  That's really a false positive rate of 1 which seems like the opposite effect.  Interpreting a 0 as the lower limit of 1e-9 seems more intuitive behavior when receiving an out-of-bounds argument.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcutil/68)

Fix range check in bloom filter false positive rate

---

bloom/merkleblock_test.go

The test would have erroneously printed the function address instead of the received bytes if it failed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcutil/73)

bloom: Correct merkle block test error print.

---

.travis.yml

Now that Go 1.6 has been released, remove the old Go versions from the configurations tested by TravisCI and add the latest point releases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcutil/72)

Update TravisCI for Go 1.6.

---

.travis.yml

The `vet` tool moved into the Go source tree as of Go 1.5.  Its previous location in the `x/tools` repo was deprecated at that time and has now been removed.
This commit updates the `.travis.yml` configuration to avoid fetching vet from the old location and to simply use the version now available as part of the standard Go install.
Also, while here, remove the check for changing to tool path since it is no longer needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcutil/74)

TravisCI: Remove external go vet reference.

---

bloom/example_test.go
bloom/filter.go

This changes several places which call the Bytes method of a ShaHash to
simply use a slice of it in order to avoid the extra unnecessary copies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btcsuite/btcutil/76)

bloom: Avoid a few unnecessary hash copies.

---

block.go
block_test.go
bloom/example_test.go
bloom/filter.go
bloom/filter_test.go
bloom/merkleblock.go
bloom/merkleblock_test.go
coinset/coins.go
coinset/coins_test.go
hdkeychain/extendedkey.go
tx.go
tx_test.go
txsort/txsort.go
txsort/txsort_test.go
wif.go

**This PR requires btcsuite/btcd#729.**
This updates all code in the main package and subpackages to make use of the new `chainhash` package since the old `wire.ShaHash` type and functions have been removed in favor of the abstracted package.
Also, since this required API changes anyways and the hash algorithm is no longer tied specifically to SHA, all other functions throughout the code base which had `Sha` in their name have been changed to `Hash` so they are not incorrectly implying the hash algorithm.
The following is an overview of the changes:
- Update all references to `wire.ShaHash` to the new `chainhash.Hash` type
- Rename the following functions and update all references:
- `Block.Sha` -> `Hash`
- `Block.TxSha` -> `TxHash`
- `Tx.Sha` -> `Hash`
- `bloom.Filter.AddShaHash` -> …

Update for recent chainhash-related API changes.

---

hdkeychain/extendedkey.go
hdkeychain/extendedkey_test.go

BIP32 keys serialize the depth as a uint8 over the wire.  I noticed
uint16 was being used and that the depth was being taken modulo 256
during serialization.
This seems like a bug, as the behaviour is not described in the BIP,
and also introduces incompatibilities which can be hard to make sense
of.  For example, the parent fingerprint should be 0x00000000 for a key
of depth zero, whereas with the existing code if depth=256, then the
serialization will specify 0 depth but still set a parent fingerprint.

hdkeychain: BIP32 maximum depth is 255

---

hdkeychain/extendedkey.go
hdkeychain/extendedkey_test.go

Putting the test code in the same package makes it easier for forks since they don't have to change the import paths as much.
Also, address a few style and consistent nits while here:
- Prefer `t.Fatalf` over `t.Errorf` followed by a return
- Use the consistent style of starting a test function comments with the test name
- Prefix test errors by the function being called instead of the one doing the calling since the caller itself is already logged by the test framework
- Check err in max depth test before checking the returned key is nil

hdkeychain: Consolidate tests into package.

---

hdkeychain/extendedkey_test.go

This adds the new test vectors added to BIP32 on 2017-02-24 which test hardened derivation with leading zeros.

hdkeychain: Add new test vector 3 tests.

---

README.md
base58/README.md
bloom/README.md
coinset/README.md
hdkeychain/README.md
txsort/README.md

The github markdown interpreter has been changed such that it no longer allows spaces in between the brackets and parenthesis of links.  This updates all of the markdown files accordingly.
While here, it also corrects a couple of inconsistencies in regards to other `README.md` files in the project.

multi: Update markdown files for GFM changes.

---

hdkeychain/extendedkey.go

Allow users to create custom ExtendedKeys by exporting the newExtendedKey function.
The comment is updated to reflect that this function is only intended to be used
by custom applications.
Addresses #99

Export NewExtendedKey

---

address.go
address_test.go
bech32/README.md
bech32/bech32.go
bech32/bech32_test.go
bech32/doc.go
bech32/example_test.go
internal_test.go

This PR implements the Bech32 address format as specified in BIP 173: https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki
Test are modeled after the Python reference implementation (https://github.com/sipa/bech32/blob/master/ref/python/tests.py) to ensure compatibility.

Add Bech32 address format package.

---

block.go
tx.go

This PR adds a number of utility messages that will be useful for callers interacting with blocks and transactions that contain witness data: 
- The first new method `btcutil.Block.BytesNoWitness` provides a helper message to generate a serialized version of a block _without_ any witness data (if any). 
- The second new method `btcutil.Tx.WitnessHash` is equivelant to `tx.Hash` but instead returns the `wtxid` of a transaction. 
- The finally added method is `btcutil.Tx.HasWitness`, which is ideneitcal to `tx.HasWitness`, but caches the results. This is a useful performance optimization as a transaction may potentially have thousands of inputs, so we avoid interacting over them repeatedly during block validation and other contexts. 
NOTE: This PR requires btcsuite/btcd#656

Add utility functions for blocks and transactions witness data 

---

gcs/builder/builder.go
gcs/builder/builder_test.go
gcs/gcs.go
gcs/gcs_test.go
gcs/gcsbench_test.go

In this PR, we update the BIP 158 generation code to match the latest BIP changes. The notable changes are:
* regular filter no longer includes the txid
* we now use distinct `M` and `N` values rather than setting `P` as it results in a small improvement
* the regular filter now uses the prev output scripts rather than the outpoint as it achieves better compression 
* there's no longer an extended filter
* when indexing scripts, we skip all `OP_RETURN` outputs

gcs+gcs/builder: update BIP 158 generation code to match latest BIP changes

---

gcs/builder/builder.go
gcs/builder/builder_test.go

In this commit, we remove the AddScript method as it's no longer used,
and AddEntry should be used in place for adding pkScripts to the
filters.

gcs/builder: remove the AddScript method as it's no longer used

---

gcs/gcs.go
gcs/gcs_test.go
gcs/gcsbench_test.go

This PR proposes a different gcs filter querying mechanism, intended for having better performance as the number of query entries surpasses the number of elements in the filter. 
As the number of elements in the query grows, allocating and sorting the elements begins to dominate the runtime. The solution then for large queries is inspired by a hash join, which makes no assumptions on the input ordering of either set. Since the number of filters is ultimately bounded by the block size, the filter entries are chosen as the hash index so that the setup latency is minimized.
Complexity
========
Number of filter entries: F
Number of query entries: Q
Assumption: Q > F
Setup
------
|                 | Regular        | Hash       | 
|----------|-------------|----------|
| Keying    | Theta (Q) …

[gcs] HashMatchAny: faster filter matches for large queries

---

address.go
address_test.go

This PR fixes a bug where BTCs default chain params from `chaincfg` are being used instead of the `defaultNet` when trying to decode a wallet address in `DecodeAddress`.
A user may want to override the default values of `chaincfg` by passing in a different set of `defaultNet` params, however `DecodeAddress` will currently throw `ErrUnknownAddressType` if the P2PKH or P2SH values do not match the default hardcoded values found in `btcd/chaincfg`.
An additional benefit to this change is that P2PKH and P2SH values are scoped to the network instead of checking ALL values that were configured with `chaincfg`

use defaultnet params instead of btc chaincfg for decode address

---

psbt/partial_input.go
psbt/psbt.go
psbt/utils.go

Fuzzer found two panics:
first one:
```
panic: runtime error: index out of range [3] with length 1
goroutine 1 [running]:
encoding/binary.littleEndian.Uint32(...)
/usr/local/Cellar/go/1.13/libexec/src/encoding/binary/binary.go:63
github.com/btcsuite/btcutil/psbt.(*PInput).deserialize(0xc0004c3db0, 0x12f3760, 0xc00009e2d0, 0xc0004c3df0, 0x1062de6)
/Users/nsa/go/src/github.com/btcsuite/btcutil/psbt/partial_input.go:153 +0x1be6
github.com/btcsuite/btcutil/psbt.Fuzz_partial_input_serialization(0x5010000, 0x4, 0x4, 0x3)
/Users/nsa/go/src/github.com/btcsuite/btcutil/psbt/partial_input_serialization.go:13 +0xf2
```
second one:
```
panic: runtime error: makeslice: len out of range
goroutine 1 [running]:
github.com/btcsuite/btcutil/psbt.getKey(0x12f3760, 0xc0000988a0, 0x8, 0x149d438, 0x203000, …
```

psbt: fix two deserialization bugs

---

block_test.go
tx.go
tx_test.go

If the witness hash is populated in the cache before the `HasWitness` method is invoked, it results in a nil pointer deference.
Added a breaking test that reproduces the behaviour; then a few assertions using dummy witness data.
Issue: btcsuite/btcd#1543
Related PR: btcsuite/btcutil#156

Fix nil pointer dereference when WitnessHash is called before HasWitness

---

psbt/sort.go
psbt/sort_test.go
psbt/utils.go
psbt/utils_test.go

To be able to implement PSBT funding in `btcwallet` we need some common utility functions added and some exported to be used externall.
We also add the ability to sort a PSBT according to [BIP 69](https://github.com/bitcoin/bips/blob/master/bip-0069.mediawiki). The difference to the normal wire TX sort is that the partial inputs and outputs that must match the wire transaction's `TxIn` and `TxOut` are sorted as well.

psbt: add/export new utility functions and BIP 69 in-place sort

---

hdkeychain/extendedkey.go

This PR fixes 'hardended'/'hardned' to 'hardened' in the godocs.

Fix some typos in docs

---

hdkeychain/extendedkey_test.go

This PR fixes typo in `hdkeychain/extendedkey_test.go`

hdkeychain: fix trivial typo

---

wif_test.go

Use subtests to split cases, and add new ones, notably for decoding invalid WIFs.
Increases coverage of `wif.go` from 73% to **98%**.

Improve test coverage of WIF decoder/encoder

---

psbt/partial_input.go
psbt/psbt_test.go
psbt/signer.go
psbt/updater.go

Fixes https://github.com/lightningnetwork/lnd/issues/4400.
Wallets that include the fix for the CVE-2020-14199 vulnerability always include the full non-witness UTXO even if the output being spent is a witness output.
To restore compatibility with those wallets, [Bitcoin Core removed the sanity checks on partial inputs](https://github.com/bitcoin/bitcoin/pull/19215).
This PR does the same for the `btcutil/psbt` library.

psbt: restore compatibility with wallets that patch CVE-2020-14199

---

hdkeychain/extendedkey.go

This function should only `by` used by applications that need to create custom ExtendedKeys. => This function should only `be` used by applications that need to create custom ExtendedKeys

Tiny grammar correction

---

hdkeychain/extendedkey.go
hdkeychain/extendedkey_test.go

|GH| #179 | https://github.com/btcsuite/btcd/pull/1617 |
-|-|-
This adds a new method to the `ExtendedKey` type that allows cloning the extended key with custom HD version bytes. It does not mutate the original extended key on which the method is called.
Added some tests to demonstrate the utility of this method, i.e., conversion between standard and [**`SLIP-0132`**](https://github.com/satoshilabs/slips/blob/master/slip-0132.md) extended keys.

hdkeychain: add CloneWithVersion to set custom HD version bytes

---

address.go
bech32/bech32_test.go

Go no longer allows it. The FIX is a good demonstration on the why. ;-)

Drop string construction from integers

---

hdkeychain/bench_test.go
hdkeychain/doc.go
hdkeychain/example_test.go
hdkeychain/extendedkey.go
hdkeychain/extendedkey_test.go

Fixes issue #172.
This issue affects 1 in 256 hardened key derivations.  For standard BIP-44 accounts, this affects the coin and account derivations, so 1 in 128 accounts will not be compatible with other BIP-44 implementations.
The intention is that wallet implementations using btcutil can use the `IsAffectedByIssue172` call to check if they are affected, and potentially migrate (or ask the user to create a new wallet).

Correct BIP-32 derivation issue

---

bech32/bech32.go
bech32/bech32_test.go
bech32/error.go
bech32/example_test.go

This PR brings a host of improvements to the bech32 package, back porting from the following commits:
* decred/dcrd@9b88dd0
* decred/dcrd@3a0dce1
* decred/dcrd@3cfb088
**The public interface of the package remains unchanged**, of course not including new public methods.
* Improved error handling using dedicated error types. Programmatically detect if the errors produced are the expected ones.
* Improve test coverage to test more corner cases. Added test vectors from Bitcoin Core.
* Add a benchmark for a full encode/decode cycle of a bech32 string.
* Add a new function `DecodeNoLimit`, for decoding large bech32 encoded strings. It does NOT validate against the BIP-173 maximum length allowed for bech32 strings.
* Automatically convert the HRP to lowercase in `Encode` function.
* Improve …

bech32: back port improvements from decred/dcrd

---

psbt/utils.go
psbt/utils_test.go

Otherwise, a malformed packet would panic on this check since the NonWitness.TxOut field did not have the required TxOuts necessary.

psbt: bounds check SumUtxoInputValues with NonWitness.TxOut indexing

---

bech32/bech32.go
bech32/bech32_test.go
bech32/error.go
bech32/version.go

In this commit, we add two new package level functions: `EncodeM`, and
`DecodeGeneric`. The new encode method is intended to allow callers to
specify that they want to use the new bech32m checksum. This should be
used when encoding segwit addresses with version 1 and beyond. The new
`DecodeGeneric` function allows a caller to decode a bech32 and bech32m
string with a single function. A new return value is added which is the
version of the returned bech32 string, which allows callers to perform
additional segwit addr validation (v1+ should use bech32m etc).
We opted to add new functions rather than modifying the existing
functions to not cause a breaking API change, as most uses in the wild
can just use the existing functions, and only taproot related logic/code
needs to worry about the …

bech32: add new EncodeM and DecodeGeneric functions for bech32
